name: mo_hub
description: A Flutter app blending Instagram Reels and adult video site concepts.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  video_player: ^2.5.1
  image_picker: ^1.1.2
  shared_preferences: ^2.1.1
  animations: ^2.0.4
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
